
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/STARTER-team03
owner: ucsb-cs156-s24
repo_name: STARTER-team03
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDk2NzQ0","is_bot":false,"login":"andrewpengucsb","name":""},"headRefName":"ap-restaurantIt","number":17,"title":"Add restaurant integration tests","url":"https://github.com/ucsb-cs156-s24/STARTER-team03/pull/17"},{"author":{"id":"MDQ6VXNlcjU2MDk2NzQ0","is_bot":false,"login":"andrewpengucsb","name":""},"headRefName":"ap-refactorWiremock","number":16,"title":"Factor out common wiremock/playwright code from web tests","url":"https://github.com/ucsb-cs156-s24/STARTER-team03/pull/16"},{"author":{"id":"MDQ6VXNlcjU2MDk2NzQ0","is_bot":false,"login":"andrewpengucsb","name":""},"headRefName":"ap-restaurant","number":4,"title":"Add Restaurants e2e tests","url":"https://github.com/ucsb-cs156-s24/STARTER-team03/pull/4"}]
